server:
  # Configuration of Spring Boot embedded Tomcat server (java -jar matchmakers.jar)
  servlet:
    contextPath: ""
  port: "${PORT:8443}"
  http:
    port: 8080
endpoints:
  jmx:
    domain: matchmakers
logging:
  config: "classpath:matchmakers-logback.xml"
spring:
  jmx:
    default-domain: matchmakers
  data:
    rest:
      defaultMediaType: application/json
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update # create | update | validate | create-drop
    properties:
      net.sf.ehcache.configurationResourceName: matchmakers-ehcache.xml
      hibernate:
        default_schema: public
        show_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    url: "${DB_URL:jdbc:postgresql://db:5432/matchmakers}"
    username: "${DB_USERNAME:matchmakers}"
    password: "${DB_PASSWORD:matchmakers}"
    driver-class-name: org.postgresql.Driver
  flyway:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-migration-properties
    enabled: false
    sqlMigrationSuffix: .sql
    validate-on-migrate: false
    table: DB_MIGRATION_HISTORY
    baselineOnMigrate: true
    schemas: public
application:
  url:
    frontend: "${URL_FRONTEND:https://matchmakers.herokuapp.com}"
    backend: "${URL_BACKEND:https://matchmakers.herokuapp.com/api}"
    ats: "https://www.workablestg5.com"
  roles:
    admin:
      access-token: admin # Change in PRD with a UUID
  mail:
    from:
      address: "no-reply@workable.com"
      host: "auth.smtp.1and1.co.uk"
      port: 587 # 25
      username: "antonakos@workable.com"
      password: "Password!"
    to:
      registration:
        pending: "antonakos@workable.com"
        validated: "antonakos@workable.com"
        completed: "antonakos@workable.com"
      interview:
        requested: "antonakos@workable.com"
      admins: "antonakos@workable.com"
